import pygame
from game.player import Player

class InputHandler:
    def __init__(self, player: Player):
        self.player = player

    def handle_events(self):
        """
        Handles the events generated by the user.

        Returns:
            int or None: The key code of the key pressed by the user, or None if no key was pressed.
        """
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                quit()
            if event.type == pygame.KEYDOWN:
                print(event.key)
                return event.key
        return None
