import pygame
from game.problem import Action

class InputHandler:
    """
    Handles user input events.

    Attributes:
        None

    Methods:
        __init__(): Initializes the InputHandler object.
        handle_events(): Handles the events generated by the user.
    """

    def __init__(self):
        """
        Initializes the InputHandler object.
        """
        pass

    def handle_events(self):
        """
        Handles the events generated by the user.

        Returns:
            int or None: The key code of the key pressed by the user, or None if no key was pressed.
        """
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                quit()
            if event.type == pygame.KEYDOWN:
                return Action(event.key)
        return None
